# Generated by Django 3.1.6 on 2021-04-16 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('section', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(default='', max_length=8)),
                ('type', models.CharField(default='U', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
                ('quantity', models.CharField(default='', max_length=30)),
                ('profile', models.CharField(default='avatar.jpg', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('profile', models.CharField(default='avatar.jpg', max_length=30)),
                ('email', models.CharField(default='', max_length=30)),
                ('phone', models.CharField(default='', max_length=30)),
                ('address', models.CharField(default='', max_length=30)),
                ('log', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.login')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(default='', max_length=30)),
                ('status', models.CharField(default='pending', max_length=5)),
                ('cartid', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.cart')),
                ('customerid', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('place', models.CharField(default=0, max_length=30)),
                ('email', models.CharField(default='', max_length=30)),
                ('log', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.login')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription', models.CharField(default='', max_length=30)),
                ('doctorid', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.doctor')),
                ('userid', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('log', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.login')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='', max_length=30)),
                ('type', models.CharField(default='', max_length=5)),
                ('doctorid', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.doctor')),
                ('userid', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='log',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.login'),
        ),
        migrations.CreateModel(
            name='Consult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(default='', max_length=100)),
                ('doctorid', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.doctor')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='productid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='userid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('cardnumber', models.CharField(max_length=30)),
                ('expmonth', models.CharField(max_length=30)),
                ('expyear', models.CharField(max_length=30)),
                ('cvv', models.CharField(default='', max_length=30)),
                ('balance', models.CharField(default='', max_length=30)),
                ('customerid', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Appoinment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultid', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.consult')),
                ('doctorid', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.doctor')),
                ('userid', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
